[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
# typeCheckingMode = "standard"
# typeCheckingMode = "strict"

[language-server.markdown-oxide]
markdown-oxide = { command = "markdown-oxide" }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true


# WEBLANGS AND JSON

[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
language-servers = ["vscode-css-language-server"]
auto-format = true

[[language]]
name = "scss"
scope = "source.scss"
file-types = ["scss"]
language-servers = ["vscode-css-language-server"]
auto-format = true

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[[language]]
name = "html"
scope = "text.html"
file-types = ["html", "htm"]
language-servers = ["vscode-html-language-server"]
auto-format = true

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[[language]]
name = "json"
scope = "source.json"
file-types = ["json"]
language-servers = ["vscode-json-language-server"]
auto-format = true

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]
